### PR TITLE
Hankyen scene integration

### PR DESCRIPTION
**Pull request by hankyen0315**
@secminhr @t510599 @a91082900 
Please check whether your features can be correctly executed in the DemoPuzzleScene.

### CODE REVIEW

**Comment by secminhr** [comment]
There's a Collider-MovePlatform layer, not really sure if something is using it.

**Comment by t510599** [comment]
It works well on my part.
Thank you.

**Comment by hankyen0315** [comment]
> There's a Collider-MovePlatform layer, not really sure if something is using it.

change in next commit

**Comment by secminhr** [comment]
Seems good. Nice work.

**Comment by a91082900** [comment]
It works. Thank you.

**Review by secminhr — APPROVED** [review]

**Pull request merged**
