### PR TITLE
multi-player

### PR DESCRIPTION
**Pull request by secminhr**
1. single player mode (switch via Shift)
2. local multi-player (WASD, arrow key at the same time)
3. Character as Obstacle (Character collide)

### CODE REVIEW

**Comment by secminhr** [comment]
This pr is now ready to merge if the reviewer considers it completes the feature.

**Comment by secminhr** [comment]
PlayerMode currently is only for debugging, but maybe it can be used to indicate the real playing mode in future. We don't know.

**Review by hankyen0315 — APPROVED** [review]
只能說他太強了

**Comment by t510599** [comment]
好強 m(_ _)m

**Pull request merged**
